### PR TITLE
feat: Additional types

### PR DESCRIPTION
**Pull request by dominiklessel**
This PR adds support for additional types. Our team uses types like `docs:` or `refactor:` and we would like to increase the version number for these as well.

### CODE REVIEW

**Comment by dominiklessel** [comment]
@caarlos0 Would you mind having a look at this? Thanks in advance 👍

**Comment by caarlos0** [comment]
I would say to, instead, change [this](https://github.com/caarlos0/svu/blob/master/main.go#L107-L111) to inc patch if its not major or feature, so we still keep things simple and within [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)...

**Comment by dominiklessel** [comment]
Indeed, that's way simpler. Good point!

**Comment by dominiklessel** [comment]
@caarlos0 I would consider this a breaking change. What do you think about "hiding" this behaviour behind a flag? Something like `--increment-patch-on-unknown-type`?

**Comment by caarlos0** [comment]
I think its more of a bug fix than a breaking change... as I would expect that if I call `svu next`, it should give me a bumped tag... and today sometimes it gives the same... so its more of a bug fix IMHO 🤔

**Comment by dominiklessel** [comment]
Agreed ... probably depends on how you look at it. If you are used to this behaviour and you're expecting it, this might cause some headaches.

**Comment by caarlos0** [comment]
I think its ok to change it...

**Pull request closed without merging**
